---
title: "Data Visualization - Mood Among Adolescents Depending on Types of Interpersonal Interactions"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    horizontal_layout: fill
    source_code: https://github.com/kmudiam/EDLD_proj_MAPS.git
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)
library(rio)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(colorblindr)
library(lubridate)
library(plotly)
library(gganimate)
library(ggtext)
```

Data Source {.sidebar}
==========
**Data Source**
Here is some information regarding the source of the data. Here's a cool little demographic table as well. 


Who makes teens happy? sad? anxious?
===============================
Column {.tabset data-width=700}
-----------------------------------------------------------------------


### Version 1

```{r}
#here::here()
df <- import("data/df_times_021321_wide.csv")
df_l <- import("data/df_times_021321.csv")

df <- df %>% 
  mutate(participant_id = factor(participant_id),
         device_id = factor(device_id),
         TimePoint = factor(TimePoint),
         TimeWith = factor(TimeWith)) 
    # rename("Sad" = `sad`, "Stressed" = `stressed`, "Anxious" = `anxious`, "Supported" = `supported`, "Happy" = `happy`, "Angry" = `angry`, "Scared" = `scared`, "Calm" =  `calm`, "Confident" = `confident`, "Lonely" = `lonely`, "Rejected" = `rejected`, "Included" = `included`)

#could use mutate_at to save some effort here & below
#df  <- df %>% mutate_at(c("participant_id", "device_id","TimePoint","TimeWith"), factor)

df_l <- df_l %>% 
  mutate(participant_id = factor(participant_id),
         device_id = factor(device_id),
         TimePoint = factor(TimePoint),
         question_id = factor(question_id),
         string_answer = factor(string_answer))

df <- df %>% 
  mutate(scared_sev = if_else(scared>3, 1, 0),
         scared_sev = factor(scared_sev),
         mfq_sev = if_else(mfq > 8, 1, 0),
         mfq_sev = factor(mfq_sev))

df_l <- df_l %>% 
    mutate(scared_sev = if_else(scared>3, 1, 0),
         scared_sev = factor(scared_sev),
         mfq_sev = if_else(mfq > 8, 1, 0),
         mfq_sev = factor(mfq_sev))

# df %>% 
#   ggplot(aes(mfq_sev)) +
#   geom_bar(aes(y = stat(count)))

df_bub <- df %>% 
  select(participant_id, TimeWith, scared_sev, happy, sad, stressed, anxious, supported) %>% 
  pivot_longer(cols = c(happy, sad, stressed, anxious, supported),
               values_drop_na = T) %>% 
  mutate(name = factor(name),
         name = fct_relevel(name, c("sad", "stressed", "anxious", "supported", "happy"))) %>%
  filter(TimeWith != "")


df_bub <- df_bub %>% 
  group_by(TimeWith, name) %>% 
  mutate(mean = mean(value, na.rm = T)) #can I include this all within the ggplot function?

# df_bub_mean <- df_bub %>%
#   dplyr::select(TimeWith, name, mean) %>%
#   group_by(TimeWith, name) %>%
#   unique()

ggplot(df_bub, 
       aes(x = TimeWith, y = name, size = mean)) + 
  geom_point(aes(fill = name,
                 color = name),
             shape = 21) + #, show.legend = F) +
    scale_fill_OkabeIto() +
    scale_color_OkabeIto() +
  theme_minimal() +
  theme(legend.position = "none",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank(),
        plot.title = element_text(size=10, hjust=0)) +
  scale_size_continuous(range = c(1, 25)) + 
  geom_text(aes(label = round(mean,0)), size = 4) +
  labs(title = "Severity of Emotion After Spending Time Alone or With Certain People",
       x = "Time Spent With", 
       y = " ") +
  scale_x_discrete(labels = c('Alone','Co-Students','Co-Workers', "Family", "Friends", "Partner")) +
  scale_y_discrete(labels = c("Sad", "Stressed", "Anxious", "Supported", "Happy"))
```


### Version 2

```{r}
ggplot(df_bub, 
       aes(x = TimeWith, y = name, size = mean)) + 
  geom_point(aes(fill = name,
                 color = name),
             shape = 21) + #, show.legend = F) +
    scale_fill_OkabeIto() +
    scale_color_OkabeIto() +
  theme_minimal() +
  theme(legend.position = "none",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank(),
      #  axis.text.x = element_text(angle = 45, vjust = 1, hjust=1), 
        plot.title = element_text(face= "bold", hjust=0)) +
  scale_size_continuous(range = c(1, 25)) +
  geom_text(aes(label = round(mean,0)), size = 4) +
  labs(title = "Severity of Emotion After Spending Time With...",
       x = " ",
       y = " ") +
  scale_x_discrete(labels = c('Self','Co-Students','Co-Workers', "Family", "Friends", "Partner")) +
  scale_y_discrete(labels = c("Sad", "Stressed", "Anxious", "Supported", "Happy"))


#change font size 
#change the ascending order of something?
#make different groups, different colors? self = gray, colleagues/acquaintances = blueish, close relationships = red 
```

### Version 3
```{r}
# palette_OkabeIto
accent_OkabeIto <- palette_OkabeIto[c(5, 2, 6, 1, 4, 3, 7)]
accent_OkabeIto[1:7] <- desaturate(lighten(accent_OkabeIto[1:7]), .3)
# #accent_OkabeIto[5:7] <- darken(accent_OkabeIto[5:7], .3))
# gg_color_swatches(7) +
# scale_fill_manual(values = accent_OkabeIto)


ggplot(df_bub, 
       aes(x = TimeWith, y = name, size = mean)) + 
  geom_point(aes(fill = name,
                 color = name),
             shape = 21) + #, show.legend = F) +
  # geom_point(data = filter(df_bub, TimeWith == "alone"),
  #            fill = "blue") +
  scale_fill_manual(values = accent_OkabeIto) +
  scale_color_manual(values = accent_OkabeIto) +
  theme_minimal() +
  theme(legend.position = "none",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank(),
      #  axis.text.x = element_text(angle = 45, vjust = 1, hjust=1), 
        plot.title = element_text(hjust= -.5)) +
  scale_size_continuous(range = c(1, 25)) +
  geom_text(aes(label = round(mean,0)), size = 4) +
  labs(title = "Severity of Emotion After Spending Time With...",
       x = " ",
       y = " ") +
  scale_x_discrete(labels = c('Self','Co-Students','Co-Workers', "Family", "Friends", "Partner")) +
  scale_y_discrete(labels = c("Sad", "Stressed", "Anxious", "Supported", "Happy"))
```

What if they're already anxious to start with? 
===============================
Column {.tabset data-width=700}
-----------------------------------------------------------------------

### Version 1

```{r}
df_bub <- df_bub %>% 
  group_by(name, TimeWith, scared_sev) %>% 
  mutate(mean_scared = mean(value, na.rm = T)) %>% 
  drop_na(scared_sev)

anxsev.labs <- c("No Anxiety at Baseline", "Anxiety at Baseline")
names(anxsev.labs) <- c("0", "1")

# df_bub %>% 
#   group_by(scared_sev) %>% 
#   count()

ggplot(df_bub, 
       aes(x = TimeWith, y = name, size = mean_scared)) +
  geom_point(aes(fill = name,
                 color = name),
             shape = 21) + 
  facet_wrap(~scared_sev,
             labeller = labeller(scared_sev = anxsev.labs)) +
    scale_fill_OkabeIto() +
    scale_color_OkabeIto() +
  theme_minimal() +
  theme(legend.position = "none",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1), 
        plot.title = element_text(size=10, hjust=1)) +
  scale_size_continuous(range = c(1, 15)) +
  geom_text(aes(label = round(mean_scared,0)), size = 4) +
  labs(title = "Severity of Emotion Among Anxious and Non-Anxious Individuals After Spending Time Alone or With Certain People",
       x = "",
       y = "") +
  scale_x_discrete(labels = c('Alone','Co-Students','Co-Workers', "Family", "Friends", "Partner")) +
  scale_y_discrete(labels = c("Sad", "Stressed", "Anxious", "Supported", "Happy"))
```

### Version 2

```{r}
df_bub <- df_bub %>% 
  group_by(name, TimeWith, scared_sev) %>% 
  mutate(mean_scared = mean(value, na.rm = T)) %>% 
  drop_na(scared_sev)

anxsev.labs <- c("No Anxiety at Baseline", "Anxiety at Baseline")
#anxsev.labs_bold <- c("<span style = 'color: #C55644'>**No Anxiety** </span> at Baseline", "<span style = 'color: #C55644'>**Anxiety**</span> at Baseline")

names(anxsev.labs) <- c("0", "1")
#names(anxsev.labs_bold) <- c("0", "1")

p <- ggplot(df_bub, 
       aes(x = TimeWith, y = name, size = mean_scared)) +
  geom_point(aes(fill = name,
                 color = name),
             shape = 21) + 
  facet_wrap(~scared_sev,
             labeller = labeller(scared_sev = anxsev.labs)) +
  scale_fill_manual(values = accent_OkabeIto) +
  scale_color_manual(values = accent_OkabeIto) +
  theme_minimal() +
  theme(legend.position = "none",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, color = "gray8"),
        plot.title = element_text(size=10),
        plot.subtitle = element_text(size = 10),
        axis.text.y = element_text(color = "gray8")) +
  scale_size_continuous(range = c(1, 13)) +
  geom_text(aes(label = round(mean_scared,0)), size = 3) +
  labs(title = "Severity of <span style = >**Emotion Among Anxious and Non-Anxious Adolescents**</span>",
       subtitle = "After Spending Time With...",
       x = "",
       y = "") +
  scale_x_discrete(labels = c('Self','Co-Students','Co-Workers', "Family", "Friends", "Partner")) +
  scale_y_discrete(labels = c("Sad", "Stressed", "Anxious", "Supported", "Happy"))

p + theme(panel.spacing.x = unit(2, "lines"),
          plot.title = element_markdown(),
          plot.subtitle = element_markdown())
```

Column {.tabset data-width=150}
-----------------------------------------------------------------------

### Anxiety at Baseline

```{r}
# df_bub %>% 
#   group_by(scared_sev) %>% 
#   unique() %>% 
#   count()

anx_table <- df_bub %>%
  group_by(scared_sev) %>%
  summarise(n_distinct(participant_id))
anx_table <- as.data.frame(anx_table)
anx_table <- anx_table %>% 
  rename("Clinical Levels of Anxiety at Baseline" = scared_sev, "N" = `n_distinct(participant_id)`) %>% 
  mutate(`Clinical Levels of Anxiety at Baseline` = as.numeric(`Clinical Levels of Anxiety at Baseline`),
         N = as.numeric(N)) %>% 
mutate(`Clinical Levels of Anxiety at Baseline` = if_else(`Clinical Levels of Anxiety at Baseline`== "1", "Absent", "Present"))

knitr::kable(anx_table)
```





Changes in Mood Over Time {data-orientation=columns}
===============================
Column {.tabset data-width=700}
-----------------------------------------------------------------------

### Version 1
```{r}
# df %>% 
# select(TimePoint) %>% 
# mutate(TimePoint = as.integer(TimePoint)) %>% 
#   range()

df_line <- df %>% 
  group_by(TimePoint, mfq_sev) %>% 
  mutate(mean_sad_mfq = mean(sad, na.rm = T)) %>% 
  drop_na(mfq_sev)


# df_line %>% 
#   group_by(mfq_sev,TimePoint) %>% 
#   count() #After a certain point, there's only one data point for later timepoints. Should I stop once n gets below 5?


sad_by_dep <- ggplot(df_line, mapping = aes(as.numeric(TimePoint), mean_sad_mfq)) +
  geom_line(aes(color = mfq_sev)) +
  geom_point(shape=21, aes(color=mfq_sev, fill = mfq_sev), size=2) +
  labs(x = "Time Point",
       y = "Sadness Severity",
       title = "Average Severity of Sadness Between Depressed and Non-Depressed Adolescents Over Time") +
  scale_color_OkabeIto() +
  annotate("text", label = "Not Depressed at Baseline", x = 36.5, y = 12, color = "orange") +
  annotate("text", label = "Depressed at Baseline", x = 44, y = 45, color = "turquoise") + # There are a bunch of ways to match colors exactly.. I use https://imagecolorpicker.com/ which lets you download a screen shot of the graph and gives you the hex codes 
  theme_minimal() +
  theme(legend.position = "none",
        #panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank()) + 
  scale_x_continuous(breaks = seq(0, 60, by = 10))

ggplotly(sad_by_dep)
```

### Version 2

```{r}
sad_by_dep <- ggplot(df_line, mapping = aes(as.numeric(TimePoint), mean_sad_mfq)) +
  geom_line(aes(color = mfq_sev)) +
  geom_point(shape=21, aes(color=mfq_sev, fill = mfq_sev), size=2) +
  labs(x = "Time Point",
       y = "Sadness Severity",
       title = "Average Severity of Sadness Between Depressed and Non-Depressed Adolescents Over Time") +
  scale_color_OkabeIto() +
  annotate("text", label = "Not Depressed at Baseline", x = 36.5, y = 5, color = "#de993a") +
  annotate("text", label = "Depressed at Baseline", x = 44, y = 40, color = "#49b3d1") + # There are a bunch of ways to match colors exactly.. I use https://imagecolorpicker.com/ which lets you download a screen shot of the graph and gives you the hex codes 
  theme_minimal() +
  theme(legend.position = "none",
        #panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank()) + 
  scale_x_continuous(breaks = seq(0, 60, by = 10))

ggplotly(sad_by_dep)

# I love that this is interactive and that you directly labeled the lines. I added the labels a little closer to the lines and matched the colors because at first glance I didn't realize you were labeling the lines (it looked like you were labeling maybe a threshold?)

# I'm a little confused about the "time point" variable here - maybe give the units? Is it years or months? At a certain point, why does everyone in the sample no longer show any sadness? And what is happening at ~20 when the orange graph spikes up? Did they give any explanation for that anomaly in the data? If they did, maybe you could label what is happening there?

```
